float atomicMin(inout float _Mem, float _Data);
float atomicMin(inout float _Mem, float _Data, int _Scope, int _Storage, int _Sem);
double atomicMin(inout double _Mem, double _Data);
double atomicMin(inout double _Mem, double _Data, int _Scope, int _Storage, int _Sem);

float atomicMax(inout float _Mem, float _Data);
float atomicMax(inout float _Mem, float _Data, int _Scope, int _Storage, int _Sem);
double atomicMax(inout double _Mem, double _Data);
double atomicMax(inout double _Mem, double _Data, int _Scope, int _Storage, int _Sem);

float16_t atomicAdd(inout float16_t _Mem, float16_t _Data);
float16_t atomicAdd(inout float16_t _Mem, float16_t _Data, int _Scope, int _Storage, int _Sem);

float16_t atomicMin(inout float16_t _Mem, float16_t _Data);
float16_t atomicMin(inout float16_t _Mem, float16_t _Data, int _Scope, int _Storage, int _Sem);

float16_t atomicMax(inout float16_t _Mem, float16_t _Data);
float16_t atomicMax(inout float16_t _Mem, float16_t _Data, int _Scope, int _Storage, int _Sem);

float16_t atomicExchange(inout float16_t _Mem, float16_t _Data);
float16_t atomicExchange(inout float16_t _Mem, float16_t _Data, int _Scope, int _Storage, int _Sem);

float16_t atomicLoad(inout float16_t _Mem, int _Scope, int _Storage, int _Sem);

void atomicStore(inout float16_t _Mem, float16_t _Data, int _Scope, int _Storage, int _Sem);

float imageAtomicMin(image2D _Image, ivec2 _P, float _Data);
float imageAtomicMin(iimage2D _Image, ivec2 _P, float _Data);
float imageAtomicMin(uimage2D _Image, ivec2 _P, float _Data);
float imageAtomicMin(image3D _Image, ivec3 _P, float _Data);
float imageAtomicMin(iimage3D _Image, ivec3 _P, float _Data);
float imageAtomicMin(uimage3D _Image, ivec3 _P, float _Data);
float imageAtomicMin(imageCube _Image, ivec3 _P, float _Data);
float imageAtomicMin(iimageCube _Image, ivec3 _P, float _Data);
float imageAtomicMin(uimageCube _Image, ivec3 _P, float _Data);
float imageAtomicMin(imageBuffer _Image, int _P, float _Data);
float imageAtomicMin(iimageBuffer _Image, int _P, float _Data);
float imageAtomicMin(uimageBuffer _Image, int _P, float _Data);
float imageAtomicMin(image2DArray _Image, ivec3 _P, float _Data);
float imageAtomicMin(iimage2DArray _Image, ivec3 _P, float _Data);
float imageAtomicMin(uimage2DArray _Image, ivec3 _P, float _Data);
float imageAtomicMin(imageCubeArray _Image, ivec3 _P, float _Data);
float imageAtomicMin(iimageCubeArray _Image, ivec3 _P, float _Data);
float imageAtomicMin(uimageCubeArray _Image, ivec3 _P, float _Data);
float imageAtomicMin(image1D _Image, int _P, float _Data);
float imageAtomicMin(iimage1D _Image, int _P, float _Data);
float imageAtomicMin(uimage1D _Image, int _P, float _Data);
float imageAtomicMin(image1DArray _Image, ivec2 _P, float _Data);
float imageAtomicMin(iimage1DArray _Image, ivec2 _P, float _Data);
float imageAtomicMin(uimage1DArray _Image, ivec2 _P, float _Data);
float imageAtomicMin(image2DRect _Image, ivec2 _P, float _Data);
float imageAtomicMin(iimage2DRect _Image, ivec2 _P, float _Data);
float imageAtomicMin(uimage2DRect _Image, ivec2 _P, float _Data);
float imageAtomicMin(image2DMS _Image, ivec2 _P, int _Sample, float _Data);
float imageAtomicMin(iimage2DMS _Image, ivec2 _P, int _Sample, float _Data);
float imageAtomicMin(uimage2DMS _Image, ivec2 _P, int _Sample, float _Data);
float imageAtomicMin(image2DMSArray _Image, ivec3 _P, int _Sample, float _Data);
float imageAtomicMin(iimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data);
float imageAtomicMin(uimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data);

float imageAtomicMin(image2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(iimage2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(uimage2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(image3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(iimage3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(uimage3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(imageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(iimageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(uimageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(imageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(iimageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(uimageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(image2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(iimage2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(uimage2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(imageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(iimageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(uimageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(image1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(iimage1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(uimage1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(image1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(iimage1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(uimage1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(image2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(iimage2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(uimage2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(image2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(iimage2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(uimage2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(image2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(iimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMin(uimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);

float imageAtomicMax(image2D _Image, ivec2 _P, float _Data);
float imageAtomicMax(iimage2D _Image, ivec2 _P, float _Data);
float imageAtomicMax(uimage2D _Image, ivec2 _P, float _Data);
float imageAtomicMax(image3D _Image, ivec3 _P, float _Data);
float imageAtomicMax(iimage3D _Image, ivec3 _P, float _Data);
float imageAtomicMax(uimage3D _Image, ivec3 _P, float _Data);
float imageAtomicMax(imageCube _Image, ivec3 _P, float _Data);
float imageAtomicMax(iimageCube _Image, ivec3 _P, float _Data);
float imageAtomicMax(uimageCube _Image, ivec3 _P, float _Data);
float imageAtomicMax(imageBuffer _Image, int _P, float _Data);
float imageAtomicMax(iimageBuffer _Image, int _P, float _Data);
float imageAtomicMax(uimageBuffer _Image, int _P, float _Data);
float imageAtomicMax(image2DArray _Image, ivec3 _P, float _Data);
float imageAtomicMax(iimage2DArray _Image, ivec3 _P, float _Data);
float imageAtomicMax(uimage2DArray _Image, ivec3 _P, float _Data);
float imageAtomicMax(imageCubeArray _Image, ivec3 _P, float _Data);
float imageAtomicMax(iimageCubeArray _Image, ivec3 _P, float _Data);
float imageAtomicMax(uimageCubeArray _Image, ivec3 _P, float _Data);
float imageAtomicMax(image1D _Image, int _P, float _Data);
float imageAtomicMax(iimage1D _Image, int _P, float _Data);
float imageAtomicMax(uimage1D _Image, int _P, float _Data);
float imageAtomicMax(image1DArray _Image, ivec2 _P, float _Data);
float imageAtomicMax(iimage1DArray _Image, ivec2 _P, float _Data);
float imageAtomicMax(uimage1DArray _Image, ivec2 _P, float _Data);
float imageAtomicMax(image2DRect _Image, ivec2 _P, float _Data);
float imageAtomicMax(iimage2DRect _Image, ivec2 _P, float _Data);
float imageAtomicMax(uimage2DRect _Image, ivec2 _P, float _Data);
float imageAtomicMax(image2DMS _Image, ivec2 _P, int _Sample, float _Data);
float imageAtomicMax(iimage2DMS _Image, ivec2 _P, int _Sample, float _Data);
float imageAtomicMax(uimage2DMS _Image, ivec2 _P, int _Sample, float _Data);
float imageAtomicMax(image2DMSArray _Image, ivec3 _P, int _Sample, float _Data);
float imageAtomicMax(iimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data);
float imageAtomicMax(uimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data);

float imageAtomicMax(image2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(iimage2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(uimage2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(image3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(iimage3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(uimage3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(imageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(iimageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(uimageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(imageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(iimageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(uimageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(image2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(iimage2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(uimage2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(imageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(iimageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(uimageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(image1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(iimage1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(uimage1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(image1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(iimage1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(uimage1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(image2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(iimage2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(uimage2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(image2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(iimage2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(uimage2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(image2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(iimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicMax(uimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
