#define GL_EXT_shader_atomic_float 1

float atomicAdd(inout float _Mem, float _Data);
float atomicAdd(inout float _Mem, float _Data, int _Scope, int _Storage, int _Sem);
double atomicAdd(inout double _Mem, double _Data);
double atomicAdd(inout double _Mem, double _Data, int _Scope, int _Storage, int _Sem);

float atomicExchange(inout float _Mem, float _Data);
float atomicExchange(inout float _Mem, float _Data, int _Scope, int _Storage, int _Sem);
double atomicExchange(inout double _Mem, double _Data);
double atomicExchange(inout double _Mem, double _Data, int _Scope, int _Storage, int _Sem);

float atomicLoad(inout float _Mem, int _Scope, int _Storage, int _Sem);
double atomicLoad(inout double _Mem, int _Scope, int _Storage, int _Sem);

void atomicStore(inout float _Mem, float _Data, int _Scope, int _Storage, int _Sem);
void atomicStore(inout double _Mem, double _Data, int _Scope, int _Storage, int _Sem);

float imageAtomicAdd(image2D _Image, ivec2 _P, float _Data);
float imageAtomicAdd(iimage2D _Image, ivec2 _P, float _Data);
float imageAtomicAdd(uimage2D _Image, ivec2 _P, float _Data);
float imageAtomicAdd(image3D _Image, ivec3 _P, float _Data);
float imageAtomicAdd(iimage3D _Image, ivec3 _P, float _Data);
float imageAtomicAdd(uimage3D _Image, ivec3 _P, float _Data);
float imageAtomicAdd(imageCube _Image, ivec3 _P, float _Data);
float imageAtomicAdd(iimageCube _Image, ivec3 _P, float _Data);
float imageAtomicAdd(uimageCube _Image, ivec3 _P, float _Data);
float imageAtomicAdd(imageBuffer _Image, int _P, float _Data);
float imageAtomicAdd(iimageBuffer _Image, int _P, float _Data);
float imageAtomicAdd(uimageBuffer _Image, int _P, float _Data);
float imageAtomicAdd(image2DArray _Image, ivec3 _P, float _Data);
float imageAtomicAdd(iimage2DArray _Image, ivec3 _P, float _Data);
float imageAtomicAdd(uimage2DArray _Image, ivec3 _P, float _Data);
float imageAtomicAdd(imageCubeArray _Image, ivec3 _P, float _Data);
float imageAtomicAdd(iimageCubeArray _Image, ivec3 _P, float _Data);
float imageAtomicAdd(uimageCubeArray _Image, ivec3 _P, float _Data);
float imageAtomicAdd(image1D _Image, int _P, float _Data);
float imageAtomicAdd(iimage1D _Image, int _P, float _Data);
float imageAtomicAdd(uimage1D _Image, int _P, float _Data);
float imageAtomicAdd(image1DArray _Image, ivec2 _P, float _Data);
float imageAtomicAdd(iimage1DArray _Image, ivec2 _P, float _Data);
float imageAtomicAdd(uimage1DArray _Image, ivec2 _P, float _Data);
float imageAtomicAdd(image2DRect _Image, ivec2 _P, float _Data);
float imageAtomicAdd(iimage2DRect _Image, ivec2 _P, float _Data);
float imageAtomicAdd(uimage2DRect _Image, ivec2 _P, float _Data);
float imageAtomicAdd(image2DMS _Image, ivec2 _P, int _Sample, float _Data);
float imageAtomicAdd(iimage2DMS _Image, ivec2 _P, int _Sample, float _Data);
float imageAtomicAdd(uimage2DMS _Image, ivec2 _P, int _Sample, float _Data);
float imageAtomicAdd(image2DMSArray _Image, ivec3 _P, int _Sample, float _Data);
float imageAtomicAdd(iimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data);
float imageAtomicAdd(uimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data);

float imageAtomicAdd(image2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(iimage2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(uimage2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(image3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(iimage3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(uimage3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(imageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(iimageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(uimageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(imageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(iimageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(uimageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(image2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(iimage2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(uimage2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(imageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(iimageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(uimageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(image1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(iimage1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(uimage1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(image1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(iimage1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(uimage1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(image2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(iimage2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(uimage2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(image2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(iimage2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(uimage2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(image2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(iimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicAdd(uimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);

float imageAtomicExchange(image2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(iimage2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(uimage2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(image3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(iimage3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(uimage3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(imageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(iimageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(uimageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(imageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(iimageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(uimageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(image2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(iimage2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(uimage2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(imageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(iimageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(uimageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(image1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(iimage1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(uimage1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(image1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(iimage1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(uimage1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(image2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(iimage2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(uimage2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(image2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(iimage2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(uimage2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(image2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(iimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
float imageAtomicExchange(uimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);

float imageAtomicLoad(image2D _Image, ivec2 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(iimage2D _Image, ivec2 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(uimage2D _Image, ivec2 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(image3D _Image, ivec3 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(iimage3D _Image, ivec3 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(uimage3D _Image, ivec3 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(imageCube _Image, ivec3 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(iimageCube _Image, ivec3 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(uimageCube _Image, ivec3 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(imageBuffer _Image, int _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(iimageBuffer _Image, int _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(uimageBuffer _Image, int _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(image2DArray _Image, ivec3 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(iimage2DArray _Image, ivec3 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(uimage2DArray _Image, ivec3 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(imageCubeArray _Image, ivec3 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(iimageCubeArray _Image, ivec3 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(uimageCubeArray _Image, ivec3 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(image1D _Image, int _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(iimage1D _Image, int _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(uimage1D _Image, int _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(image1DArray _Image, ivec2 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(iimage1DArray _Image, ivec2 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(uimage1DArray _Image, ivec2 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(image2DRect _Image, ivec2 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(iimage2DRect _Image, ivec2 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(uimage2DRect _Image, ivec2 _P, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(image2DMS _Image, ivec2 _P, int _Sample, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(iimage2DMS _Image, ivec2 _P, int _Sample, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(uimage2DMS _Image, ivec2 _P, int _Sample, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(image2DMSArray _Image, ivec3 _P, int _Sample, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(iimage2DMSArray _Image, ivec3 _P, int _Sample, int _Scope, int _Storage, int _Sem);
float imageAtomicLoad(uimage2DMSArray _Image, ivec3 _P, int _Sample, int _Scope, int _Storage, int _Sem);

void imageAtomicStore(image2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(iimage2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(uimage2D _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(image3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(iimage3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(uimage3D _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(imageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(iimageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(uimageCube _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(imageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(iimageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(uimageBuffer _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(image2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(iimage2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(uimage2DArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(imageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(iimageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(uimageCubeArray _Image, ivec3 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(image1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(iimage1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(uimage1D _Image, int _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(image1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(iimage1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(uimage1DArray _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(image2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(iimage2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(uimage2DRect _Image, ivec2 _P, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(image2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(iimage2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(uimage2DMS _Image, ivec2 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(image2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(iimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
void imageAtomicStore(uimage2DMSArray _Image, ivec3 _P, int _Sample, float _Data, int _Scope, int _Storage, int _Sem);
