u64vec4 imageLoad(readonly i64image2D _Image, ivec2 _P);
u64vec4 imageLoad(readonly u64image2D _Image, ivec2 _P);
i64vec4 imageLoad(readonly i64image2D _Image, ivec2 _P);
i64vec4 imageLoad(readonly u64image2D _Image, ivec2 _P);
u64vec4 imageLoad(readonly i64image3D _Image, ivec3 _P);
u64vec4 imageLoad(readonly u64image3D _Image, ivec3 _P);
i64vec4 imageLoad(readonly i64image3D _Image, ivec3 _P);
i64vec4 imageLoad(readonly u64image3D _Image, ivec3 _P);
u64vec4 imageLoad(readonly i64image2DArray _Image, ivec3 _P);
u64vec4 imageLoad(readonly u64image2DArray _Image, ivec3 _P);
i64vec4 imageLoad(readonly i64image2DArray _Image, ivec3 _P);
i64vec4 imageLoad(readonly u64image2DArray _Image, ivec3 _P);
u64vec4 imageLoad(readonly i64imageCube _Image, ivec3 _P);
u64vec4 imageLoad(readonly u64imageCube _Image, ivec3 _P);
i64vec4 imageLoad(readonly i64imageCube _Image, ivec3 _P);
i64vec4 imageLoad(readonly u64imageCube _Image, ivec3 _P);
u64vec4 imageLoad(readonly i64image1D _Image, int _P);
u64vec4 imageLoad(readonly u64image1D _Image, int _P);
i64vec4 imageLoad(readonly i64image1D _Image, int _P);
i64vec4 imageLoad(readonly u64image1D _Image, int _P);
u64vec4 imageLoad(readonly i64image1DArray _Image, ivec2 _P);
u64vec4 imageLoad(readonly u64image1DArray _Image, ivec2 _P);
i64vec4 imageLoad(readonly i64image1DArray _Image, ivec2 _P);
i64vec4 imageLoad(readonly u64image1DArray _Image, ivec2 _P);
u64vec4 imageLoad(readonly i64imageBuffer _Image, int _P);
u64vec4 imageLoad(readonly u64imageBuffer _Image, int _P);
i64vec4 imageLoad(readonly i64imageBuffer _Image, int _P);
i64vec4 imageLoad(readonly u64imageBuffer _Image, int _P);
u64vec4 imageLoad(readonly i64image2DRect _Image, ivec2 _P);
u64vec4 imageLoad(readonly u64image2DRect _Image, ivec2 _P);
i64vec4 imageLoad(readonly i64image2DRect _Image, ivec2 _P);
i64vec4 imageLoad(readonly u64image2DRect _Image, ivec2 _P);
u64vec4 imageLoad(readonly i64image2DMS _Image, ivec2 _P, int _Sample);
u64vec4 imageLoad(readonly u64image2DMS _Image, ivec2 _P, int _Sample);
i64vec4 imageLoad(readonly i64image2DMS _Image, ivec2 _P, int _Sample);
i64vec4 imageLoad(readonly u64image2DMS _Image, ivec2 _P, int _Sample);
u64vec4 imageLoad(readonly i64image2DMSArray _Image, ivec3 _P, int _Sample);
u64vec4 imageLoad(readonly u64image2DMSArray _Image, ivec3 _P, int _Sample);
i64vec4 imageLoad(readonly i64image2DMSArray _Image, ivec3 _P, int _Sample);
i64vec4 imageLoad(readonly u64image2DMSArray _Image, ivec3 _P, int _Sample);
u64vec4 imageLoad(readonly i64imageCubeArray _Image, ivec3 _P);
u64vec4 imageLoad(readonly u64imageCubeArray _Image, ivec3 _P);
i64vec4 imageLoad(readonly i64imageCubeArray _Image, ivec3 _P);
i64vec4 imageLoad(readonly u64imageCubeArray _Image, ivec3 _P);

void imageStore(writeonly i64image2D _Image, ivec2 _P, u64vec4 _Texel);
void imageStore(writeonly u64image2D _Image, ivec2 _P, u64vec4 _Texel);
void imageStore(writeonly i64image2D _Image, ivec2 _P, i64vec4 _Texel);
void imageStore(writeonly u64image2D _Image, ivec2 _P, i64vec4 _Texel);
void imageStore(writeonly i64image3D _Image, ivec3 _P, u64vec4 _Texel);
void imageStore(writeonly u64image3D _Image, ivec3 _P, u64vec4 _Texel);
void imageStore(writeonly i64image3D _Image, ivec3 _P, i64vec4 _Texel);
void imageStore(writeonly u64image3D _Image, ivec3 _P, i64vec4 _Texel);
void imageStore(writeonly i64image2DArray _Image, ivec3 _P, u64vec4 _Texel);
void imageStore(writeonly u64image2DArray _Image, ivec3 _P, u64vec4 _Texel);
void imageStore(writeonly i64image2DArray _Image, ivec3 _P, i64vec4 _Texel);
void imageStore(writeonly u64image2DArray _Image, ivec3 _P, i64vec4 _Texel);
void imageStore(writeonly i64imageCube _Image, ivec3 _P, u64vec4 _Texel);
void imageStore(writeonly u64imageCube _Image, ivec3 _P, u64vec4 _Texel);
void imageStore(writeonly i64imageCube _Image, ivec3 _P, i64vec4 _Texel);
void imageStore(writeonly u64imageCube _Image, ivec3 _P, i64vec4 _Texel);
void imageStore(writeonly i64image1D _Image, int _P, u64vec4 _Texel);
void imageStore(writeonly u64image1D _Image, int _P, u64vec4 _Texel);
void imageStore(writeonly i64image1D _Image, int _P, i64vec4 _Texel);
void imageStore(writeonly u64image1D _Image, int _P, i64vec4 _Texel);
void imageStore(writeonly i64image1DArray _Image, ivec2 _P, u64vec4 _Texel);
void imageStore(writeonly u64image1DArray _Image, ivec2 _P, u64vec4 _Texel);
void imageStore(writeonly i64image1DArray _Image, ivec2 _P, i64vec4 _Texel);
void imageStore(writeonly u64image1DArray _Image, ivec2 _P, i64vec4 _Texel);
void imageStore(writeonly i64imageBuffer _Image, int _P, u64vec4 _Texel);
void imageStore(writeonly u64imageBuffer _Image, int _P, u64vec4 _Texel);
void imageStore(writeonly i64imageBuffer _Image, int _P, i64vec4 _Texel);
void imageStore(writeonly u64imageBuffer _Image, int _P, i64vec4 _Texel);
void imageStore(writeonly i64image2DRect _Image, ivec2 _P, u64vec4 _Texel);
void imageStore(writeonly u64image2DRect _Image, ivec2 _P, u64vec4 _Texel);
void imageStore(writeonly i64image2DRect _Image, ivec2 _P, i64vec4 _Texel);
void imageStore(writeonly u64image2DRect _Image, ivec2 _P, i64vec4 _Texel);
void imageStore(writeonly i64image2DMS _Image, ivec2 _P, int _Sample, u64vec4 _Texel);
void imageStore(writeonly u64image2DMS _Image, ivec2 _P, int _Sample, u64vec4 _Texel);
void imageStore(writeonly i64image2DMS _Image, ivec2 _P, int _Sample, i64vec4 _Texel);
void imageStore(writeonly u64image2DMS _Image, ivec2 _P, int _Sample, i64vec4 _Texel);
void imageStore(writeonly i64image2DMSArray _Image, ivec3 _P, int _Sample, u64vec4 _Texel);
void imageStore(writeonly u64image2DMSArray _Image, ivec3 _P, int _Sample, u64vec4 _Texel);
void imageStore(writeonly i64image2DMSArray _Image, ivec3 _P, int _Sample, i64vec4 _Texel);
void imageStore(writeonly u64image2DMSArray _Image, ivec3 _P, int _Sample, i64vec4 _Texel);
void imageStore(writeonly i64imageCubeArray _Image, ivec3 _P, u64vec4 _Texel);
void imageStore(writeonly u64imageCubeArray _Image, ivec3 _P, u64vec4 _Texel);
void imageStore(writeonly i64imageCubeArray _Image, ivec3 _P, i64vec4 _Texel);
void imageStore(writeonly u64imageCubeArray _Image, ivec3 _P, i64vec4 _Texel);

uint64_t imageAtomicAdd(i64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicAdd(i64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicAdd(u64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicAdd(u64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicAdd(i64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAdd(i64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAdd(u64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAdd(u64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAdd(i64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAdd(i64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAdd(u64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAdd(u64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAdd(i64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAdd(i64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAdd(u64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAdd(u64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAdd(i64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicAdd(i64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicAdd(u64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicAdd(u64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicAdd(i64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicAdd(i64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicAdd(u64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicAdd(u64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicAdd(i64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicAdd(i64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicAdd(u64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicAdd(u64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicAdd(i64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicAdd(i64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicAdd(u64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicAdd(u64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicAdd(i64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicAdd(i64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicAdd(u64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicAdd(u64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicAdd(i64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicAdd(i64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicAdd(u64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicAdd(u64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicAdd(i64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAdd(i64imageCubeArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAdd(u64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAdd(u64imageCubeArray _Image, ivec3 _P, int64_t _Data);

uint64_t imageAtomicMin(i64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicMin(i64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicMin(u64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicMin(u64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicMin(i64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMin(i64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMin(u64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMin(u64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMin(i64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMin(i64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMin(u64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMin(u64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMin(i64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMin(i64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMin(u64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMin(u64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMin(i64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicMin(i64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicMin(u64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicMin(u64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicMin(i64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicMin(i64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicMin(u64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicMin(u64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicMin(i64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicMin(i64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicMin(u64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicMin(u64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicMin(i64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicMin(i64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicMin(u64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicMin(u64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicMin(i64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicMin(i64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicMin(u64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicMin(u64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicMin(i64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicMin(i64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicMin(u64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicMin(u64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicMin(i64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMin(i64imageCubeArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMin(u64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMin(u64imageCubeArray _Image, ivec3 _P, int64_t _Data);

uint64_t imageAtomicMax(i64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicMax(i64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicMax(u64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicMax(u64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicMax(i64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMax(i64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMax(u64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMax(u64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMax(i64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMax(i64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMax(u64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMax(u64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMax(i64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMax(i64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMax(u64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMax(u64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMax(i64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicMax(i64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicMax(u64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicMax(u64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicMax(i64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicMax(i64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicMax(u64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicMax(u64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicMax(i64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicMax(i64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicMax(u64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicMax(u64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicMax(i64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicMax(i64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicMax(u64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicMax(u64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicMax(i64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicMax(i64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicMax(u64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicMax(u64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicMax(i64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicMax(i64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicMax(u64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicMax(u64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicMax(i64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMax(i64imageCubeArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicMax(u64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicMax(u64imageCubeArray _Image, ivec3 _P, int64_t _Data);

uint64_t imageAtomicAnd(i64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicAnd(i64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicAnd(u64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicAnd(u64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicAnd(i64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAnd(i64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAnd(u64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAnd(u64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAnd(i64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAnd(i64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAnd(u64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAnd(u64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAnd(i64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAnd(i64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAnd(u64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAnd(u64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAnd(i64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicAnd(i64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicAnd(u64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicAnd(u64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicAnd(i64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicAnd(i64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicAnd(u64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicAnd(u64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicAnd(i64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicAnd(i64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicAnd(u64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicAnd(u64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicAnd(i64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicAnd(i64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicAnd(u64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicAnd(u64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicAnd(i64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicAnd(i64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicAnd(u64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicAnd(u64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicAnd(i64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicAnd(i64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicAnd(u64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicAnd(u64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicAnd(i64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAnd(i64imageCubeArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicAnd(u64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicAnd(u64imageCubeArray _Image, ivec3 _P, int64_t _Data);

uint64_t imageAtomicOr(i64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicOr(i64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicOr(u64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicOr(u64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicOr(i64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicOr(i64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicOr(u64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicOr(u64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicOr(i64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicOr(i64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicOr(u64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicOr(u64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicOr(i64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicOr(i64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicOr(u64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicOr(u64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicOr(i64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicOr(i64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicOr(u64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicOr(u64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicOr(i64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicOr(i64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicOr(u64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicOr(u64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicOr(i64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicOr(i64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicOr(u64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicOr(u64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicOr(i64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicOr(i64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicOr(u64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicOr(u64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicOr(i64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicOr(i64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicOr(u64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicOr(u64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicOr(i64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicOr(i64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicOr(u64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicOr(u64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicOr(i64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicOr(i64imageCubeArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicOr(u64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicOr(u64imageCubeArray _Image, ivec3 _P, int64_t _Data);

uint64_t imageAtomicXor(i64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicXor(i64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicXor(u64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicXor(u64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicXor(i64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicXor(i64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicXor(u64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicXor(u64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicXor(i64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicXor(i64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicXor(u64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicXor(u64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicXor(i64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicXor(i64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicXor(u64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicXor(u64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicXor(i64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicXor(i64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicXor(u64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicXor(u64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicXor(i64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicXor(i64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicXor(u64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicXor(u64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicXor(i64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicXor(i64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicXor(u64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicXor(u64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicXor(i64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicXor(i64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicXor(u64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicXor(u64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicXor(i64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicXor(i64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicXor(u64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicXor(u64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicXor(i64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicXor(i64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicXor(u64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicXor(u64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicXor(i64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicXor(i64imageCubeArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicXor(u64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicXor(u64imageCubeArray _Image, ivec3 _P, int64_t _Data);

uint64_t imageAtomicExchange(i64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicExchange(i64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicExchange(u64image2D _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicExchange(u64image2D _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicExchange(i64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicExchange(i64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicExchange(u64image3D _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicExchange(u64image3D _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicExchange(i64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicExchange(i64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicExchange(u64image2DArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicExchange(u64image2DArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicExchange(i64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicExchange(i64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicExchange(u64imageCube _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicExchange(u64imageCube _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicExchange(i64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicExchange(i64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicExchange(u64image1D _Image, int _P, uint64_t _Data);
int64_t imageAtomicExchange(u64image1D _Image, int _P, int64_t _Data);
uint64_t imageAtomicExchange(i64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicExchange(i64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicExchange(u64image1DArray _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicExchange(u64image1DArray _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicExchange(i64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicExchange(i64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicExchange(u64imageBuffer _Image, int _P, uint64_t _Data);
int64_t imageAtomicExchange(u64imageBuffer _Image, int _P, int64_t _Data);
uint64_t imageAtomicExchange(i64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicExchange(i64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicExchange(u64image2DRect _Image, ivec2 _P, uint64_t _Data);
int64_t imageAtomicExchange(u64image2DRect _Image, ivec2 _P, int64_t _Data);
uint64_t imageAtomicExchange(i64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicExchange(i64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicExchange(u64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicExchange(u64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicExchange(i64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicExchange(i64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicExchange(u64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Data);
int64_t imageAtomicExchange(u64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Data);
uint64_t imageAtomicExchange(i64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicExchange(i64imageCubeArray _Image, ivec3 _P, int64_t _Data);
uint64_t imageAtomicExchange(u64imageCubeArray _Image, ivec3 _P, uint64_t _Data);
int64_t imageAtomicExchange(u64imageCubeArray _Image, ivec3 _P, int64_t _Data);

uint64_t imageAtomicCompSwap(i64image2D _Image, ivec2 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(i64image2D _Image, ivec2 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(u64image2D _Image, ivec2 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(u64image2D _Image, ivec2 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(i64image3D _Image, ivec3 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(i64image3D _Image, ivec3 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(u64image3D _Image, ivec3 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(u64image3D _Image, ivec3 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(i64image2DArray _Image, ivec3 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(i64image2DArray _Image, ivec3 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(u64image2DArray _Image, ivec3 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(u64image2DArray _Image, ivec3 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(i64imageCube _Image, ivec3 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(i64imageCube _Image, ivec3 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(u64imageCube _Image, ivec3 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(u64imageCube _Image, ivec3 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(i64image1D _Image, int _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(i64image1D _Image, int _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(u64image1D _Image, int _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(u64image1D _Image, int _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(i64image1DArray _Image, ivec2 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(i64image1DArray _Image, ivec2 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(u64image1DArray _Image, ivec2 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(u64image1DArray _Image, ivec2 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(i64imageBuffer _Image, int _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(i64imageBuffer _Image, int _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(u64imageBuffer _Image, int _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(u64imageBuffer _Image, int _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(i64image2DRect _Image, ivec2 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(i64image2DRect _Image, ivec2 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(u64image2DRect _Image, ivec2 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(u64image2DRect _Image, ivec2 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(i64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(i64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(u64image2DMS _Image, ivec2 _P, int _Sample, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(u64image2DMS _Image, ivec2 _P, int _Sample, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(i64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(i64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(u64image2DMSArray _Image, ivec3 _P, int _Sample, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(u64image2DMSArray _Image, ivec3 _P, int _Sample, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(i64imageCubeArray _Image, ivec3 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(i64imageCubeArray _Image, ivec3 _P, int64_t _Compare, int64_t _Data);
uint64_t imageAtomicCompSwap(u64imageCubeArray _Image, ivec3 _P, uint64_t _Compare, uint64_t _Data);
int64_t imageAtomicCompSwap(u64imageCubeArray _Image, ivec3 _P, int64_t _Compare, int64_t _Data);
