#define GL_QCOM_cooperative_matrix_conversion 1

void bitcastQCOM(uint _SrcArr[], uint _DstArr[]);
void bitcastQCOM(uint _SrcArr[], int _DstArr[]);
void bitcastQCOM(uint _SrcArr[], float _DstArr[]);
void bitcastQCOM(uint _SrcArr[], float16_t _DstArr[]);
void bitcastQCOM(int _SrcArr[], uint _DstArr[]);
void bitcastQCOM(int _SrcArr[], int _DstArr[]);
void bitcastQCOM(int _SrcArr[], float _DstArr[]);
void bitcastQCOM(int _SrcArr[], float16_t _DstArr[]);
void bitcastQCOM(float _SrcArr[], uint _DstArr[]);
void bitcastQCOM(float _SrcArr[], int _DstArr[]);
void bitcastQCOM(float _SrcArr[], float _DstArr[]);
void bitcastQCOM(float _SrcArr[], float16_t _DstArr[]);
void bitcastQCOM(float16_t _SrcArr[], uint _DstArr[]);
void bitcastQCOM(float16_t _SrcArr[], int _DstArr[]);
void bitcastQCOM(float16_t _SrcArr[], float _DstArr[]);
void bitcastQCOM(float16_t _SrcArr[], float16_t _DstArr[]);

void extractSubArrayQCOM(uint _SrcArr[], int _StartIndex, uint _DstArr[]);
void extractSubArrayQCOM(int _SrcArr[], int _StartIndex, int _DstArr[]);
void extractSubArrayQCOM(float _SrcArr[], int _StartIndex, float _DstArr[]);
void extractSubArrayQCOM(float16_t _SrcArr[], int _StartIndex, float16_t _DstArr[]);

void vectorToCoopmatQCOM(float _Vec[], coopmat<float, gl_ScopeSubgroup, 16, 16, gl_MatrixUseA> _Cm);
void vectorToCoopmatQCOM(uint _Vec[], coopmat<float, gl_ScopeSubgroup, 16, 16, gl_MatrixUseA> _Cm);
void vectorToCoopmatQCOM(float16_t _Vec[], coopmat<float16_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseA> _Cm);
void vectorToCoopmatQCOM(uint _Vec[], coopmat<float16_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseA> _Cm);
void vectorToCoopmatQCOM(uint8_t _Vec[], coopmat<uint8_t, gl_ScopeSubgroup, 16, 32, gl_MatrixUseA> _Cm);
void vectorToCoopmatQCOM(uint _Vec[], coopmat<uint8_t, gl_ScopeSubgroup, 16, 32, gl_MatrixUseA> _Cm);
void vectorToCoopmatQCOM(int8_t _Vec[], coopmat<int8_t, gl_ScopeSubgroup, 16, 32, gl_MatrixUseA> _Cm);
void vectorToCoopmatQCOM(uint _Vec[], coopmat<int8_t, gl_ScopeSubgroup, 16, 32, gl_MatrixUseA> _Cm);
void vectorToCoopmatQCOM(float _Vec[], coopmat<float, gl_ScopeSubgroup, 8, 16, gl_MatrixUseB> _Cm);
void vectorToCoopmatQCOM(uint _Vec[], coopmat<float, gl_ScopeSubgroup, 8, 16, gl_MatrixUseB> _Cm);
void vectorToCoopmatQCOM(float16_t _Vec[], coopmat<float16_t, gl_ScopeSubgroup, 16, 8, gl_MatrixUseB> _Cm);
void vectorToCoopmatQCOM(uint _Vec[], coopmat<float16_t, gl_ScopeSubgroup, 16, 8, gl_MatrixUseB> _Cm);
void vectorToCoopmatQCOM(uint8_t _Vec[], coopmat<uint8_t, gl_ScopeSubgroup, 32, 16, gl_MatrixUseB> _Cm);
void vectorToCoopmatQCOM(uint _Vec[], coopmat<uint8_t, gl_ScopeSubgroup, 32, 16, gl_MatrixUseB> _Cm);
void vectorToCoopmatQCOM(int8_t _Vec[], coopmat<int8_t, gl_ScopeSubgroup, 32, 16, gl_MatrixUseB> _Cm);
void vectorToCoopmatQCOM(uint _Vec[], coopmat<int8_t, gl_ScopeSubgroup, 32, 16, gl_MatrixUseB> _Cm);
void vectorToCoopmatQCOM(uint _Vec[], coopmat<uint, gl_ScopeSubgroup, 8, 16, gl_MatrixUseAccumulator> _Cm);
void vectorToCoopmatQCOM(uint _Vec[], coopmat<int, gl_ScopeSubgroup, 8, 16, gl_MatrixUseAccumulator> _Cm);
void vectorToCoopmatQCOM(uint _Vec[], coopmat<float, gl_ScopeSubgroup, 8, 16, gl_MatrixUseAccumulator> _Cm);
void vectorToCoopmatQCOM(float _Vec[], coopmat<float, gl_ScopeSubgroup, 8, 16, gl_MatrixUseAccumulator> _Cm);

void coopmatToVectorQCOM(coopmat<float, gl_ScopeSubgroup, 16, 16, gl_MatrixUseA> _Cm, float _Vec[]);
void coopmatToVectorQCOM(coopmat<float, gl_ScopeSubgroup, 16, 16, gl_MatrixUseA> _Cm, uint _Vec[]);
void coopmatToVectorQCOM(coopmat<float16_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseA> _Cm, float16_t _Vec[]);
void coopmatToVectorQCOM(coopmat<float16_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseA> _Cm, uint _Vec[]);
void coopmatToVectorQCOM(coopmat<uint8_t, gl_ScopeSubgroup, 16, 32, gl_MatrixUseA> _Cm, uint8_t _Vec[]);
void coopmatToVectorQCOM(coopmat<uint8_t, gl_ScopeSubgroup, 16, 32, gl_MatrixUseA> _Cm, uint _Vec[]);
void coopmatToVectorQCOM(coopmat<int8_t, gl_ScopeSubgroup, 16, 32, gl_MatrixUseA> _Cm, int8_t _Vec[]);
void coopmatToVectorQCOM(coopmat<int8_t, gl_ScopeSubgroup, 16, 32, gl_MatrixUseA> _Cm, uint _Vec[]);
void coopmatToVectorQCOM(coopmat<float, gl_ScopeSubgroup, 8, 16, gl_MatrixUseB> _Cm, float _Vec[]);
void coopmatToVectorQCOM(coopmat<float, gl_ScopeSubgroup, 8, 16, gl_MatrixUseB> _Cm, uint _Vec[]);
void coopmatToVectorQCOM(coopmat<float16_t, gl_ScopeSubgroup, 16, 8, gl_MatrixUseB> _Cm, float16_t _Vec[]);
void coopmatToVectorQCOM(coopmat<float16_t, gl_ScopeSubgroup, 16, 8, gl_MatrixUseB> _Cm, uint _Vec[]);
void coopmatToVectorQCOM(coopmat<uint8_t, gl_ScopeSubgroup, 32, 16, gl_MatrixUseB> _Cm, uint8_t _Vec[]);
void coopmatToVectorQCOM(coopmat<uint8_t, gl_ScopeSubgroup, 32, 16, gl_MatrixUseB> _Cm, uint _Vec[]);
void coopmatToVectorQCOM(coopmat<int8_t, gl_ScopeSubgroup, 32, 16, gl_MatrixUseB> _Cm, int8_t _Vec[]);
void coopmatToVectorQCOM(coopmat<int8_t, gl_ScopeSubgroup, 32, 16, gl_MatrixUseB> _Cm, uint _Vec[]);
void coopmatToVectorQCOM(coopmat<uint, gl_ScopeSubgroup, 8, 16, gl_MatrixUseAccumulator> _Cm, uint _Vec[]);
void coopmatToVectorQCOM(coopmat<int, gl_ScopeSubgroup, 8, 16, gl_MatrixUseAccumulator> _Cm, int _Vec[]);
void coopmatToVectorQCOM(coopmat<float, gl_ScopeSubgroup, 8, 16, gl_MatrixUseAccumulator> _Cm, float _Vec[]);
void coopmatToVectorQCOM(coopmat<float, gl_ScopeSubgroup, 8, 16, gl_MatrixUseAccumulator> _Cm, uint _Vec[]);
