// [Note] The "__Function" primitive is used for LSP placeholders
// and should not be used directly in shader code.

#define GL_NV_cooperative_matrix2 1

const int gl_CooperativeMatrixClampModeUndefinedNV    = 0;
const int gl_CooperativeMatrixClampModeConstantNV     = 1;
const int gl_CooperativeMatrixClampModeClampToEdgeNV  = 2;
const int gl_CooperativeMatrixClampModeRepeatNV       = 3;
const int gl_CooperativeMatrixClampModeMirrorRepeatNV = 4;

const int gl_CooperativeMatrixReduceRowNV             = 0x1;
const int gl_CooperativeMatrixReduceColumnNV          = 0x2;
const int gl_CooperativeMatrixReduceRowAndColumnNV    = 0x3;
const int gl_CooperativeMatrixReduce2x2NV             = 0x4;

tensorLayoutNV createTensorLayoutNV(uint _Dim, uint _Mode);

tensorLayoutNV setTensorLayoutBlockSizeNV(tensorLayoutNV _T, uint _BlockSize0);
tensorLayoutNV setTensorLayoutBlockSizeNV(tensorLayoutNV _T, uint _BlockSize0, uint _BlockSize1);
tensorLayoutNV setTensorLayoutBlockSizeNV(tensorLayoutNV _T, uint _BlockSize0, uint _BlockSize1, uint _BlockSize2);
tensorLayoutNV setTensorLayoutBlockSizeNV(tensorLayoutNV _T, uint _BlockSize0, uint _BlockSize1, uint _BlockSize2, uint _BlockSize3);
tensorLayoutNV setTensorLayoutBlockSizeNV(tensorLayoutNV _T, uint _BlockSize0, uint _BlockSize1, uint _BlockSize2, uint _BlockSize3, uint _BlockSize4);

tensorLayoutNV setTensorLayoutDimensionNV(tensorLayoutNV _T, uint _Dim0);
tensorLayoutNV setTensorLayoutDimensionNV(tensorLayoutNV _T, uint _Dim0, uint _Dim1);
tensorLayoutNV setTensorLayoutDimensionNV(tensorLayoutNV _T, uint _Dim0, uint _Dim1, uint _Dim2);
tensorLayoutNV setTensorLayoutDimensionNV(tensorLayoutNV _T, uint _Dim0, uint _Dim1, uint _Dim2, uint _Dim3);
tensorLayoutNV setTensorLayoutDimensionNV(tensorLayoutNV _T, uint _Dim0, uint _Dim1, uint _Dim2, uint _Dim3, uint _Dim4);

tensorLayoutNV setTensorLayoutStrideNV(tensorLayoutNV _T, uint _S0);
tensorLayoutNV setTensorLayoutStrideNV(tensorLayoutNV _T, uint _S0, uint _S1);
tensorLayoutNV setTensorLayoutStrideNV(tensorLayoutNV _T, uint _S0, uint _S1, uint _S2);
tensorLayoutNV setTensorLayoutStrideNV(tensorLayoutNV _T, uint _S0, uint _S1, uint _S2, uint _S3);
tensorLayoutNV setTensorLayoutStrideNV(tensorLayoutNV _T, uint _S0, uint _S1, uint _S2, uint _S3, uint _S4);

tensorLayoutNV sliceTensorLayoutNV(tensorLayoutNV _T, int _Offset0, uint _Span0);
tensorLayoutNV sliceTensorLayoutNV(tensorLayoutNV _T, int _Offset0, uint _Span0, int _Offset1, uint _Span1);
tensorLayoutNV sliceTensorLayoutNV(tensorLayoutNV _T, int _Offset0, uint _Span0, int _Offset1, uint _Span1, int _Offset2, uint _Span2);
tensorLayoutNV sliceTensorLayoutNV(tensorLayoutNV _T, int _Offset0, uint _Span0, int _Offset1, uint _Span1, int _Offset2, uint _Span2, int _Offset3, uint _Span3);
tensorLayoutNV sliceTensorLayoutNV(tensorLayoutNV _T, int _Offset0, uint _Span0, int _Offset1, uint _Span1, int _Offset2, uint _Span2, int _Offset3, uint _Span3, int _Offset4, uint _Span4);

tensorLayoutNV setTensorLayoutClampValueNV(tensorLayoutNV _T, uint _Value);

tensorViewNV createTensorViewNV(uint _Dim, bool _HasDimensions, uint _P0);
tensorViewNV createTensorViewNV(uint _Dim, bool _HasDimensions, uint _P0, uint _P1);
tensorViewNV createTensorViewNV(uint _Dim, bool _HasDimensions, uint _P0, uint _P1, uint _P2);
tensorViewNV createTensorViewNV(uint _Dim, bool _HasDimensions, uint _P0, uint _P1, uint _P2, uint _P3);
tensorViewNV createTensorViewNV(uint _Dim, bool _HasDimensions, uint _P0, uint _P1, uint _P2, uint _P3, uint _P4);

tensorViewNV setTensorViewDimensionsNV(tensorViewNV _V, uint _Dim0);
tensorViewNV setTensorViewDimensionsNV(tensorViewNV _V, uint _Dim0, uint _Dim1);
tensorViewNV setTensorViewDimensionsNV(tensorViewNV _V, uint _Dim0, uint _Dim1, uint _Dim2);
tensorViewNV setTensorViewDimensionsNV(tensorViewNV _V, uint _Dim0, uint _Dim1, uint _Dim2, uint _Dim3);
tensorViewNV setTensorViewDimensionsNV(tensorViewNV _V, uint _Dim0, uint _Dim1, uint _Dim2, uint _Dim3, uint _Dim4);

tensorViewNV setTensorViewStrideNV(tensorViewNV _V, uint _S0);
tensorViewNV setTensorViewStrideNV(tensorViewNV _V, uint _S0, uint _S1);
tensorViewNV setTensorViewStrideNV(tensorViewNV _V, uint _S0, uint _S1, uint _S2);
tensorViewNV setTensorViewStrideNV(tensorViewNV _V, uint _S0, uint _S1, uint _S2, uint _S3);
tensorViewNV setTensorViewStrideNV(tensorViewNV _V, uint _S0, uint _S1, uint _S2, uint _S3, uint _S4);

tensorViewNV setTensorViewClipNV(tensorViewNV _V, uint _ClipRowOffset, uint _ClipRowSpan, uint _ClipColOffset, uint _ClipColSpan);

void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int8_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int32_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint8_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint32_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent float16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent float[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent float64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i8vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u8vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i8vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u8vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);

void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int8_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int32_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint8_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint32_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent float16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent float[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent float64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i8vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u8vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i8vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u8vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);

void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int8_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int32_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint8_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint32_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent float16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent float[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent float64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i8vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u8vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i8vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u8vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, __Function _DecodeFunc);

void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int8_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int32_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent int64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint8_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint32_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent uint64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent float16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent float[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent float64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i8vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u8vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i8vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent i64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u8vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent u64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);
void coopMatLoadTensorNV(inout coopmat _M, volatile coherent f64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View, __Function _DecodeFunc);

void coopMatStoreTensorNV(coopmat _M, volatile coherent out int8_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out int16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out int32_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out int64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out uint8_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out uint16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out uint32_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out uint64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out float16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out float[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out float64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i8vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u8vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out f16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out f32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out f64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i8vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u8vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out f16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out f32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out f64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout);

void coopMatStoreTensorNV(coopmat _M, volatile coherent out int8_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out int16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out int32_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out int64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out uint8_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out uint16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out uint32_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out uint64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out float16_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out float[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out float64_t[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i8vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u8vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out f16vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out f32vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out f64vec2[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i8vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out i64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u8vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out u64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out f16vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out f32vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);
void coopMatStoreTensorNV(coopmat _M, volatile coherent out f64vec4[] _Buf, uint _ElementOffset, tensorLayoutNV _Layout, tensorViewNV _View);

void coopMatReduceNV(out coopmat _Result, coopmat _M, int _ReduceMask, __Function _CombineOp);

void coopMatPerElementNV(out coopmat _Result, coopmat _M, __Function _ElemOp, ...);

void coopMatTransposeNV(out coopmat _Result, coopmat _M);
