#define GL_NV_cooperative_vector 1

const int gl_ComponentTypeFloat16NV            = 0;
const int gl_ComponentTypeFloat32NV            = 1;
const int gl_ComponentTypeFloat64NV            = 2;
const int gl_ComponentTypeSignedInt8NV         = 3;
const int gl_ComponentTypeSignedInt16NV        = 4;
const int gl_ComponentTypeSignedInt32NV        = 5;
const int gl_ComponentTypeSignedInt64NV        = 6;
const int gl_ComponentTypeUnsignedInt8NV       = 7;
const int gl_ComponentTypeUnsignedInt16NV      = 8;
const int gl_ComponentTypeUnsignedInt32NV      = 9;
const int gl_ComponentTypeUnsignedInt64NV      = 10;
const int gl_ComponentTypeSignedInt8PackedNV   = 1000491000;
const int gl_ComponentTypeUnsignedInt8PackedNV = 1000491001;
const int gl_ComponentTypeFloatE4M3NV          = 1000491002;
const int gl_ComponentTypeFloatE5M2NV          = 1000491003;

const int gl_CooperativeVectorMatrixLayoutRowMajorNV           = 0;
const int gl_CooperativeVectorMatrixLayoutColumnMajorNV        = 1;
const int gl_CooperativeVectorMatrixLayoutInferencingOptimalNV = 2;
const int gl_CooperativeVectorMatrixLayoutTrainingOptimalNV    = 3;

void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const int64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint8_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const uint64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float16_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float32_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulAddNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, const float64_t[] _Bias, uint _BiasOffset, int _BiasInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);

void coopVecMatMulNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const int64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint8_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const uint64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float16_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float32_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);
void coopVecMatMulNV(out coopvecNV _Result, coopvecNV _Input, int _InputInterpretation, const float64_t[] _Matrix, uint _MatrixOffset, int _MatrixInterpretation, uint _M, uint _K, int _MatrixLayout, bool _Transpose, uint _MatrixStride);

void coopVecLoadNV(out coopvecNV _Vector, volatile coherent int8_t[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent i8vec2[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent i8vec3[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent i8vec4[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent int16_t[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent i16vec2[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent i16vec3[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent i16vec4[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent int32_t[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent i32vec2[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent i32vec3[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent i32vec4[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent int64_t[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent i64vec2[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent i64vec3[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent i64vec4[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent uint8_t[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent u8vec2[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent u8vec3[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent u8vec4[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent uint16_t[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent u16vec2[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent u16vec3[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent u16vec4[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent uint32_t[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent u32vec2[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent u32vec3[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent u32vec4[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent uint64_t[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent u64vec2[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent u64vec3[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent u64vec4[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent float16_t[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent f16vec2[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent f16vec3[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent f16vec4[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent float32_t[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent f32vec2[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent f32vec3[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent f32vec4[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent float64_t[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent f64vec2[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent f64vec3[] _Buffer, uint _Offset);
void coopVecLoadNV(out coopvecNV _Vector, volatile coherent f64vec4[] _Buffer, uint _Offset);

void coopVecStoreNV(coopvecNV _Vector, volatile coherent int8_t[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent i8vec2[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent i8vec3[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent i8vec4[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent int16_t[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent i16vec2[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent i16vec3[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent i16vec4[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent int32_t[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent i32vec2[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent i32vec3[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent i32vec4[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent int64_t[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent i64vec2[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent i64vec3[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent i64vec4[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent uint8_t[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent u8vec2[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent u8vec3[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent u8vec4[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent uint16_t[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent u16vec2[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent u16vec3[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent u16vec4[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent uint32_t[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent u32vec2[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent u32vec3[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent u32vec4[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent uint64_t[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent u64vec2[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent u64vec3[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent u64vec4[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent float16_t[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent f16vec2[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent f16vec3[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent f16vec4[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent float32_t[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent f32vec2[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent f32vec3[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent f32vec4[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent float64_t[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent f64vec2[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent f64vec3[] _Buffer, uint _Offset);
void coopVecStoreNV(coopvecNV _Vector, volatile coherent f64vec4[] _Buffer, uint _Offset);

void coopVecOuterProductAccumulateNV(const coopvecNV _Vector1, const coopvecNV _Vector2, int8_t[] _Buffer, uint _Offset, uint _Stride, int _MatrixLayout, int _MatrixInterpretation);
void coopVecOuterProductAccumulateNV(const coopvecNV _Vector1, const coopvecNV _Vector2, int16_t[] _Buffer, uint _Offset, uint _Stride, int _MatrixLayout, int _MatrixInterpretation);
void coopVecOuterProductAccumulateNV(const coopvecNV _Vector1, const coopvecNV _Vector2, int32_t[] _Buffer, uint _Offset, uint _Stride, int _MatrixLayout, int _MatrixInterpretation);
void coopVecOuterProductAccumulateNV(const coopvecNV _Vector1, const coopvecNV _Vector2, int64_t[] _Buffer, uint _Offset, uint _Stride, int _MatrixLayout, int _MatrixInterpretation);
void coopVecOuterProductAccumulateNV(const coopvecNV _Vector1, const coopvecNV _Vector2, uint8_t[] _Buffer, uint _Offset, uint _Stride, int _MatrixLayout, int _MatrixInterpretation);
void coopVecOuterProductAccumulateNV(const coopvecNV _Vector1, const coopvecNV _Vector2, uint16_t[] _Buffer, uint _Offset, uint _Stride, int _MatrixLayout, int _MatrixInterpretation);
void coopVecOuterProductAccumulateNV(const coopvecNV _Vector1, const coopvecNV _Vector2, uint32_t[] _Buffer, uint _Offset, uint _Stride, int _MatrixLayout, int _MatrixInterpretation);
void coopVecOuterProductAccumulateNV(const coopvecNV _Vector1, const coopvecNV _Vector2, uint64_t[] _Buffer, uint _Offset, uint _Stride, int _MatrixLayout, int _MatrixInterpretation);
void coopVecOuterProductAccumulateNV(const coopvecNV _Vector1, const coopvecNV _Vector2, float16_t[] _Buffer, uint _Offset, uint _Stride, int _MatrixLayout, int _MatrixInterpretation);
void coopVecOuterProductAccumulateNV(const coopvecNV _Vector1, const coopvecNV _Vector2, float32_t[] _Buffer, uint _Offset, uint _Stride, int _MatrixLayout, int _MatrixInterpretation);
void coopVecOuterProductAccumulateNV(const coopvecNV _Vector1, const coopvecNV _Vector2, float64_t[] _Buffer, uint _Offset, uint _Stride, int _MatrixLayout, int _MatrixInterpretation);

void coopVecReduceSumAccumulateNV(const coopvecNV _Vector, int8_t[] _Buffer, uint _Offset);
void coopVecReduceSumAccumulateNV(const coopvecNV _Vector, int16_t[] _Buffer, uint _Offset);
void coopVecReduceSumAccumulateNV(const coopvecNV _Vector, int32_t[] _Buffer, uint _Offset);
void coopVecReduceSumAccumulateNV(const coopvecNV _Vector, int64_t[] _Buffer, uint _Offset);
void coopVecReduceSumAccumulateNV(const coopvecNV _Vector, uint8_t[] _Buffer, uint _Offset);
void coopVecReduceSumAccumulateNV(const coopvecNV _Vector, uint16_t[] _Buffer, uint _Offset);
void coopVecReduceSumAccumulateNV(const coopvecNV _Vector, uint32_t[] _Buffer, uint _Offset);
void coopVecReduceSumAccumulateNV(const coopvecNV _Vector, uint64_t[] _Buffer, uint _Offset);
void coopVecReduceSumAccumulateNV(const coopvecNV _Vector, float16_t[] _Buffer, uint _Offset);
void coopVecReduceSumAccumulateNV(const coopvecNV _Vector, float32_t[] _Buffer, uint _Offset);
void coopVecReduceSumAccumulateNV(const coopvecNV _Vector, float64_t[] _Buffer, uint _Offset);
